<?php

namespace Database\Seeders;

use App\Models\BankModel;
use Illuminate\Database\Seeder;

class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['nama' => 'Bank Bri','kode' => '002'],
            ['nama' => 'Bank Ekspor Indonesia','kode' => '003'],
            ['nama' => 'Bank Mandiri','kode' => '008'],
            ['nama' => 'Bank Bni','kode' => '009'],
            ['nama' => 'Bank Bni Syariah','kode' => '427'],
            ['nama' => 'Bank Danamon','kode' => '011'],
            ['nama' => 'Permata Bank','kode' => '013'],
            ['nama' => 'Bank Bca','kode' => '014'],
            ['nama' => 'Bank Bii','kode' => '016'],
            ['nama' => 'Bank Panin','kode' => '019'],
            ['nama' => 'Bank Arta Niaga Kencana','kode' => '020'],
            ['nama' => 'Bank Niaga','kode' => '022'],
            ['nama' => 'Bank Buana Ind','kode' => '023'],
            ['nama' => 'Bank Lippo','kode' => '026'],
            ['nama' => 'Bank Nisp','kode' => '028'],
            ['nama' => 'American Express Bank Ltd','kode' => '030'],
            ['nama' => 'Citibank N.A.','kode' => '031'],
            ['nama' => 'Jp. Morgan Chase Bank, N.A.','kode' => '032'],
            ['nama' => 'Bank Of America, N.A','kode' => '033'],
            ['nama' => 'Ing Indonesia Bank','kode' => '034'],
            ['nama' => 'Bank Multicor Tbk.','kode' => '036'],
            ['nama' => 'Bank Artha Graha','kode' => '037'],
            ['nama' => 'Bank Credit Agricole Indosuez','kode' => '039'],
            ['nama' => 'The Bangkok Bank Comp. Ltd','kode' => '040'],
            ['nama' => 'The Hongkong & Shanghai B.C.','kode' => '041'],
            ['nama' => 'The Bank Of Tokyo Mitsubishi Ufj Ltd','kode' => '042'],
            ['nama' => 'Bank Sumitomo Mitsui Indonesia','kode' => '045'],
            ['nama' => 'Bank Dbs Indonesia','kode' => '046'],
            ['nama' => 'Bank Resona Perdania','kode' => '047'],
            ['nama' => 'Bank Mizuho Indonesia','kode' => '048'],
            ['nama' => 'Standard Chartered Bank','kode' => '050'],
            ['nama' => 'Bank Abn Amro','kode' => '052'],
            ['nama' => 'Bank Keppel Tatlee Buana','kode' => '053'],
            ['nama' => 'Bank Capital Indonesia, Tbk.','kode' => '054'],
            ['nama' => 'Bank Bnp Paribas Indonesia','kode' => '057'],
            ['nama' => 'Bank Uob Indonesia','kode' => '058'],
            ['nama' => 'Korea Exchange Bank Danamon','kode' => '059'],
            ['nama' => 'Rabobank Internasional Indonesia','kode' => '060'],
            ['nama' => 'Anz Panin Bank','kode' => '061'],
            ['nama' => 'Deutsche Bank Ag.','kode' => '067'],
            ['nama' => 'Bank Woori Indonesia','kode' => '068'],
            ['nama' => 'Bank Of China Limited','kode' => '069'],
            ['nama' => 'Bank Bumi Arta','kode' => '076'],
            ['nama' => 'Bank Ekonomi','kode' => '087'],
            ['nama' => 'Bank Antardaerah','kode' => '088'],
            ['nama' => 'Bank Haga','kode' => '089'],
            ['nama' => 'Bank Ifi','kode' => '093'],
            ['nama' => 'Bank Century, Tbk.','kode' => '095'],
            ['nama' => 'Bank Mayapada','kode' => '097'],
            ['nama' => 'Bank Jabar','kode' => '110'],
            ['nama' => 'Bank Dki','kode' => '111'],
            ['nama' => 'Bpd Diy','kode' => '112'],
            ['nama' => 'Bank Jateng','kode' => '113'],
            ['nama' => 'Bank Jatim','kode' => '114'],
            ['nama' => 'Bpd Jambi','kode' => '115'],
            ['nama' => 'Bpd Aceh','kode' => '116'],
            ['nama' => 'Bank Sumut','kode' => '117'],
            ['nama' => 'Bank Nagari','kode' => '118'],
            ['nama' => 'Bank Riau','kode' => '119'],
            ['nama' => 'Bank Sumsel','kode' => '120'],
            ['nama' => 'Bank Lampung','kode' => '121'],
            ['nama' => 'Bpd Kalsel','kode' => '122'],
            ['nama' => 'Bpd Kalimantan Barat','kode' => '123'],
            ['nama' => 'Bpd Kaltim','kode' => '124'],
            ['nama' => 'Bpd Kalteng','kode' => '125'],
            ['nama' => 'Bpd Sulsel','kode' => '126'],
            ['nama' => 'Bank Sulut','kode' => '127'],
            ['nama' => 'Bpd Ntb','kode' => '128'],
            ['nama' => 'Bpd Bali','kode' => '129'],
            ['nama' => 'Bank Ntt','kode' => '130'],
            ['nama' => 'Bank Maluku','kode' => '131'],
            ['nama' => 'Bpd Papua','kode' => '132'],
            ['nama' => 'Bank Bengkulu','kode' => '133'],
            ['nama' => 'Bpd Sulawesi Tengah','kode' => '134'],
            ['nama' => 'Bank Sultra','kode' => '135'],
            ['nama' => 'Bank Nusantara Parahyangan','kode' => '145'],
            ['nama' => 'Bank Swadesi','kode' => '146'],
            ['nama' => 'Bank Muamalat','kode' => '147'],
            ['nama' => 'Bank Mestika','kode' => '151'],
            ['nama' => 'Bank Metro Express','kode' => '152'],
            ['nama' => 'Bank Shinta Indonesia','kode' => '153'],
            ['nama' => 'Bank Maspion','kode' => '157'],
            ['nama' => 'Bank Hagakita','kode' => '159'],
            ['nama' => 'Bank Ganesha','kode' => '161'],
            ['nama' => 'Bank Windu Kentjana','kode' => '162'],
            ['nama' => 'Halim Indonesia Bank','kode' => '164'],
            ['nama' => 'Bank Harmoni International','kode' => '166'],
            ['nama' => 'Bank Kesawan','kode' => '167'],
            ['nama' => 'Bank Tabungan Negara (Persero)','kode' => '200'],
            ['nama' => 'Bank Himpunan Saudara 1906, Tbk .','kode' => '212'],
            ['nama' => 'Bank Tabungan Pensiunan Nasional','kode' => '213'],
            ['nama' => 'Bank Swaguna','kode' => '405'],
            ['nama' => 'Bank Jasa Arta','kode' => '422'],
            ['nama' => 'Bank Mega','kode' => '426'],
            ['nama' => 'Bank Jasa Jakarta','kode' => '427'],
            ['nama' => 'Bank Bukopin','kode' => '441'],
            ['nama' => 'Bank Syariah Mandiri','kode' => '451'],
            ['nama' => 'Bank Bisnis Internasional','kode' => '459'],
            ['nama' => 'Bank Sri Partha','kode' => '466'],
            ['nama' => 'Bank Jasa Jakarta','kode' => '472'],
            ['nama' => 'Bank Bintang Manunggal','kode' => '484'],
            ['nama' => 'Bank Bumiputera','kode' => '485'],
            ['nama' => 'Bank Yudha Bhakti','kode' => '490'],
            ['nama' => 'Bank Mitraniaga','kode' => '491'],
            ['nama' => 'Bank Agro Niaga','kode' => '494'],
            ['nama' => 'Bank Indomonex','kode' => '498'],
            ['nama' => 'Bank Royal Indonesia','kode' => '501'],
            ['nama' => 'Bank Alfindo','kode' => '503'],
            ['nama' => 'Bank Syariah Mega','kode' => '506'],
            ['nama' => 'Bank Ina Perdana','kode' => '513'],
            ['nama' => 'Bank Harfa','kode' => '517'],
            ['nama' => 'Prima Master Bank','kode' => '520'],
            ['nama' => 'Bank Persyarikatan Indonesia','kode' => '521'],
            ['nama' => 'Bank Akita','kode' => '525'],
            ['nama' => 'Liman International Bank','kode' => '526'],
            ['nama' => 'Anglomas Internasional Bank','kode' => '531'],
            ['nama' => 'Bank Dipo International','kode' => '523'],
            ['nama' => 'Bank Kesejahteraan Ekonomi','kode' => '535'],
            ['nama' => 'Bank Uib','kode' => '536'],
            ['nama' => 'Bank Artos Ind','kode' => '542'],
            ['nama' => 'Bank Purba Danarta','kode' => '547'],
            ['nama' => 'Bank Multi Arta Sentosa','kode' => '548'],
            ['nama' => 'Bank Mayora','kode' => '553'],
            ['nama' => 'Bank Index Selindo','kode' => '555'],
            ['nama' => 'Bank Victoria International','kode' => '566'],
            ['nama' => 'Bank Eksekutif','kode' => '558'],
            ['nama' => 'Centratama Nasional Bank','kode' => '559'],
            ['nama' => 'Bank Fama Internasional','kode' => '562'],
            ['nama' => 'Bank Sinar Harapan Bali','kode' => '564'],
            ['nama' => 'Bank Harda','kode' => '567'],
            ['nama' => 'Bank Finconesia','kode' => '945'],
            ['nama' => 'Bank Merincorp','kode' => '946'],
            ['nama' => 'Bank Maybank Indocorp','kode' => '947'],
            ['nama' => 'Bank Ocbc Indonesia','kode' => '948'],
            ['nama' => 'Bank China Trust Indonesia','kode' => '949'],
            ['nama' => 'Bank Commonwealth','kode' => '950'],
            ['nama' => 'Bank Bjb Syariah','kode' => '425'],
            ['nama' => 'Bpr Ks Karyajatnika Sedaya','kode' => '688'],
            ['nama' => 'Indosat Dompetku','kode' => '789'],
            ['nama' => 'Telkomsel Tcash','kode' => '911'],
            ['nama' => 'Linkaja','kode' => '911'],
        ];

        foreach ($data as $d) {
            BankModel::create($d);
        }

    }
}
