<?php

namespace Database\Seeders;

use App\Models\ClcoaModel;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClcoaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        ClcoaModel::insert([
            ['id' =>'1', 'kdrek1' => '1', 'kdrek2' => '0', 'kdrek3' => '0', 'kdrek' => '0', 'uraian' => 'AKTIVA', 'type' => 'H'],
            ['id' =>'2', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '0', 'kdrek' => '0', 'uraian' => 'Aktiva Lancar', 'type' => 'S'],
            ['id' =>'3', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '10', 'uraian' => 'Kas', 'type' => 'C'],
            ['id' =>'4', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '10.001', 'uraian' => 'Kas Kecil', 'type' => 'D'],
            ['id' =>'5', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '10.002', 'uraian' => 'Bank BCA PT. Onanmedia', 'type' => 'D'],
            ['id' =>'6', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '10.003', 'uraian' => 'Bank Mandiri PT. Onanmedia', 'type' => 'D'],
            ['id' =>'7', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '10.004', 'uraian' => 'Kas Tunai / Kasir', 'type' => 'D'],
            ['id' =>'8', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '10.005', 'uraian' => 'Bank BRI  PT.  Onanmedia', 'type' => 'D'],
            ['id' =>'9', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '10.006', 'uraian' => 'Bank BNI  PT.  Onanmedia', 'type' => 'D'],
            ['id' =>'10', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '10.007', 'uraian' => 'Deposito', 'type' => 'D'],
            ['id' =>'11', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '10.008', 'uraian' => 'Kas Karyawan', 'type' => 'D'],
            ['id' =>'12', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '10.009', 'uraian' => 'Pemindahan Dana Bank', 'type' => 'D'],
            ['id' =>'13', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '11', 'uraian' => 'Piutang', 'type' => 'C'],
            ['id' =>'14', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '11.001', 'uraian' => 'Piutang Usaha', 'type' => 'D'],
            ['id' =>'15', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '11.002', 'uraian' => 'Piutang Pihak Berelasi', 'type' => 'D'],
            ['id' =>'16', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '11.003', 'uraian' => 'Piutang Lain Lain', 'type' => 'D'],
            ['id' =>'17', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '3', 'kdrek' => '12', 'uraian' => 'Persediaan', 'type' => 'C'],
            ['id' =>'18', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '3', 'kdrek' => '12.001', 'uraian' => 'Persediaan', 'type' => 'D'],
            ['id' =>'19', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '3', 'kdrek' => '12.002', 'uraian' => 'Persediaan Dalam Proses', 'type' => 'D'],
            ['id' =>'20', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '4', 'kdrek' => '13', 'uraian' => 'Pembayaran Dimuka', 'type' => 'C'],
            ['id' =>'21', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '4', 'kdrek' => '13.001', 'uraian' => 'Pembayaran di muka ', 'type' => 'D'],
            ['id' =>'22', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '4', 'kdrek' => '13.002', 'uraian' => 'Deposit', 'type' => 'D'],
            ['id' =>'23', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '4', 'kdrek' => '13.003', 'uraian' => 'Pajak Dibayar Dimuka (PPh 23)', 'type' => 'D'],
            ['id' =>'24', 'kdrek1' => '1', 'kdrek2' => '1', 'kdrek3' => '4', 'kdrek' => '13.004', 'uraian' => 'Pajak Dibayar Dimuka (PPN)', 'type' => 'D'],
            ['id' =>'25', 'kdrek1' => '1', 'kdrek2' => '2', 'kdrek3' => '0', 'kdrek' => '0', 'uraian' => 'Aktiva tetap', 'type' => 'S'],
            ['id' =>'26', 'kdrek1' => '1', 'kdrek2' => '2', 'kdrek3' => '1', 'kdrek' => '15', 'uraian' => 'tanah, bangunan, dan peralatan', 'type' => 'C'],
            ['id' =>'27', 'kdrek1' => '1', 'kdrek2' => '2', 'kdrek3' => '1', 'kdrek' => '15.001', 'uraian' => 'Renovasi dan Lainnya', 'type' => 'D'],
            ['id' =>'28', 'kdrek1' => '1', 'kdrek2' => '2', 'kdrek3' => '1', 'kdrek' => '15.002', 'uraian' => 'Furniture dan Fixture', 'type' => 'D'],
            ['id' =>'29', 'kdrek1' => '1', 'kdrek2' => '2', 'kdrek3' => '1', 'kdrek' => '15.003', 'uraian' => 'Komputer & Perlengkapan Kantor', 'type' => 'D'],
            ['id' =>'30', 'kdrek1' => '1', 'kdrek2' => '2', 'kdrek3' => '2', 'kdrek' => '16', 'uraian' => 'Akumulasi Depresiasi', 'type' => 'C'],
            ['id' =>'31', 'kdrek1' => '1', 'kdrek2' => '2', 'kdrek3' => '2', 'kdrek' => '16.001', 'uraian' => 'Akumulasi Depresiasi Renovasi dan Lainnya', 'type' => 'D'],
            ['id' =>'32', 'kdrek1' => '1', 'kdrek2' => '2', 'kdrek3' => '2', 'kdrek' => '16.002', 'uraian' => 'Akumulasi Furniture dan Fixture', 'type' => 'D'],
            ['id' =>'33', 'kdrek1' => '1', 'kdrek2' => '2', 'kdrek3' => '2', 'kdrek' => '16.003', 'uraian' => 'Akumulasi Komputer & Perlengkapan Kantor', 'type' => 'D'],
            ['id' =>'34', 'kdrek1' => '1', 'kdrek2' => '2', 'kdrek3' => '3', 'kdrek' => '17', 'uraian' => 'asset lainnya', 'type' => 'C'],
            ['id' =>'35', 'kdrek1' => '1', 'kdrek2' => '2', 'kdrek3' => '3', 'kdrek' => '17.001', 'uraian' => 'Asset dalam penyelesaian (Uang Muka Project)', 'type' => 'D'],
            ['id' =>'36', 'kdrek1' => '1', 'kdrek2' => '2', 'kdrek3' => '3', 'kdrek' => '17.002', 'uraian' => 'Asset lancar lainnya ', 'type' => 'D'],
            ['id' =>'37', 'kdrek1' => '2', 'kdrek2' => '0', 'kdrek3' => '0', 'kdrek' => '0', 'uraian' => 'PASIVA', 'type' => 'H'],
            ['id' =>'38', 'kdrek1' => '2', 'kdrek2' => '1', 'kdrek3' => '0', 'kdrek' => '0', 'uraian' => 'Kewajiban', 'type' => 'S'],
            ['id' =>'39', 'kdrek1' => '2', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '300', 'uraian' => 'Hutang Lancar', 'type' => 'C'],
            ['id' =>'40', 'kdrek1' => '2', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '300.001', 'uraian' => 'Hutang Usaha', 'type' => 'D'],
            ['id' =>'41', 'kdrek1' => '2', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '300.002', 'uraian' => 'Hutang Pihak Berelasi', 'type' => 'D'],
            ['id' =>'42', 'kdrek1' => '2', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '300.003', 'uraian' => 'Hutang Lain-lain', 'type' => 'D'],
            ['id' =>'43', 'kdrek1' => '2', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '301', 'uraian' => 'Hutang Pajak', 'type' => 'C'],
            ['id' =>'44', 'kdrek1' => '2', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '301.001', 'uraian' => 'Pajak Keluaran', 'type' => 'D'],
            ['id' =>'45', 'kdrek1' => '2', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '301.002', 'uraian' => 'PPh Final', 'type' => 'D'],
            ['id' =>'46', 'kdrek1' => '2', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '301.003', 'uraian' => 'PPh Final atas sewa', 'type' => 'D'],
            ['id' =>'47', 'kdrek1' => '2', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '301.004', 'uraian' => 'PPh atas Jasa', 'type' => 'D'],
            ['id' =>'48', 'kdrek1' => '2', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '301.005', 'uraian' => 'PPh atas Gaji', 'type' => 'D'],
            ['id' =>'49', 'kdrek1' => '2', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '301.006', 'uraian' => 'Pajak Pinalty', 'type' => 'D'],
            ['id' =>'50', 'kdrek1' => '2', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '301.007', 'uraian' => 'Biaya Dicatat Dimuka', 'type' => 'D'],
            ['id' =>'51', 'kdrek1' => '2', 'kdrek2' => '1', 'kdrek3' => '3', 'kdrek' => '303', 'uraian' => 'Hutang Lain-lain', 'type' => 'C'],
            ['id' =>'52', 'kdrek1' => '2', 'kdrek2' => '1', 'kdrek3' => '3', 'kdrek' => '303.001', 'uraian' => 'Hutang Lain-lain', 'type' => 'D'],
            ['id' =>'53', 'kdrek1' => '3', 'kdrek2' => '0', 'kdrek3' => '0', 'kdrek' => '0', 'uraian' => 'Modal dan Ekuitas', 'type' => 'H'],
            ['id' =>'54', 'kdrek1' => '3', 'kdrek2' => '1', 'kdrek3' => '0', 'kdrek' => '0', 'uraian' => 'Modal dan Ekuitas', 'type' => 'S'],
            ['id' =>'55', 'kdrek1' => '3', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '500', 'uraian' => 'Modal', 'type' => 'C'],
            ['id' =>'56', 'kdrek1' => '3', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '500.001', 'uraian' => 'Modal Saham', 'type' => 'D'],
            ['id' =>'57', 'kdrek1' => '3', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '500.002', 'uraian' => 'A', 'type' => 'D'],
            ['id' =>'58', 'kdrek1' => '3', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '500.003', 'uraian' => 'B', 'type' => 'D'],
            ['id' =>'59', 'kdrek1' => '3', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '500.004', 'uraian' => 'C', 'type' => 'D'],
            ['id' =>'60', 'kdrek1' => '3', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '500.005', 'uraian' => 'Deviden', 'type' => 'D'],
            ['id' =>'61', 'kdrek1' => '3', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '501', 'uraian' => 'Ekuitas', 'type' => 'C'],
            ['id' =>'62', 'kdrek1' => '3', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '501.001', 'uraian' => 'Laba Rugi Tahun Sebelumnya', 'type' => 'D'],
            ['id' =>'63', 'kdrek1' => '3', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '501.002', 'uraian' => 'Laba Rugi Current Year', 'type' => 'D'],
            ['id' =>'64', 'kdrek1' => '3', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '501.003', 'uraian' => 'Prive', 'type' => 'D'],
            ['id' =>'65', 'kdrek1' => '4', 'kdrek2' => '0', 'kdrek3' => '0', 'kdrek' => '0', 'uraian' => 'Pendapatan', 'type' => 'H'],
            ['id' =>'66', 'kdrek1' => '4', 'kdrek2' => '1', 'kdrek3' => '0', 'kdrek' => '0', 'uraian' => 'Pendapatan- Pendapatan', 'type' => 'S'],
            ['id' =>'67', 'kdrek1' => '4', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '400', 'uraian' => 'Pendapatan usaha', 'type' => 'C'],
            ['id' =>'68', 'kdrek1' => '4', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '400.001', 'uraian' => 'Pendapatan atas Penjualan', 'type' => 'D'],
            ['id' =>'69', 'kdrek1' => '4', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '400.002', 'uraian' => 'Pendapatan atas Project', 'type' => 'D'],
            ['id' =>'70', 'kdrek1' => '4', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '400.003', 'uraian' => 'Pendapatan Atas Komisi', 'type' => 'D'],
            ['id' =>'71', 'kdrek1' => '4', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '400.004', 'uraian' => 'Pengembalian Dana Pinjaman dr Lain-lain', 'type' => 'D'],
            ['id' =>'72', 'kdrek1' => '4', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '800', 'uraian' => 'Pendapatan lain- lain', 'type' => 'C'],
            ['id' =>'73', 'kdrek1' => '4', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '800.001', 'uraian' => 'Pendapatan Bunga', 'type' => 'D'],
            ['id' =>'74', 'kdrek1' => '4', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '800.002', 'uraian' => 'Pendapatan Lainnya', 'type' => 'D'],
            ['id' =>'75', 'kdrek1' => '5', 'kdrek2' => '0', 'kdrek3' => '0', 'kdrek' => '0', 'uraian' => 'Beban', 'type' => 'H'],
            ['id' =>'76', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '0', 'kdrek' => '0', 'uraian' => 'Beban Operasional', 'type' => 'S'],
            ['id' =>'77', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '600', 'uraian' => 'Biaya Operasional', 'type' => 'C'],
            ['id' =>'78', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '600.001', 'uraian' => 'Biaya Pembelian Barang', 'type' => 'D'],
            ['id' =>'79', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '600.002', 'uraian' => 'Biaya Pengiriman Barang', 'type' => 'D'],
            ['id' =>'80', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '600.003', 'uraian' => 'Biaya Penjualan', 'type' => 'D'],
            ['id' =>'81', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '600.002', 'uraian' => 'Biaya Pengiriman Barang', 'type' => 'D'],
            ['id' =>'82', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '600.004', 'uraian' => 'Biaya Representasi', 'type' => 'D'],
            ['id' =>'83', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '600.005', 'uraian' => 'Biaya Donasi/Sponshorship', 'type' => 'D'],
            ['id' =>'84', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '600.006', 'uraian' => 'Biaya Entertainment', 'type' => 'D'],
            ['id' =>'85', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '600.007', 'uraian' => 'Biaya Komisi', 'type' => 'D'],
            ['id' =>'86', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '600.008', 'uraian' => 'Biaya telephone', 'type' => 'D'],
            ['id' =>'87', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '600.009', 'uraian' => 'Biaya Listrik, Air, Internet', 'type' => 'D'],
            ['id' =>'88', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '1', 'kdrek' => '600.011', 'uraian' => 'Biaya Operasional Lainnya', 'type' => 'D'],
            ['id' =>'89', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '601', 'uraian' => 'Beban Pajak', 'type' => 'C'],
            ['id' =>'90', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '601.001', 'uraian' => 'Biaya PPH 21', 'type' => 'D'],
            ['id' =>'91', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '601.002', 'uraian' => 'Biaya PPN Tidak Dapat Dikreditkan', 'type' => 'D'],
            ['id' =>'92', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '601.003', 'uraian' => 'Biaya PPh Final', 'type' => 'D'],
            ['id' =>'93', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '601.004', 'uraian' => 'Biaya PPh 23', 'type' => 'D'],
            ['id' =>'94', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '601.005', 'uraian' => 'Biaya PPh 25', 'type' => 'D'],
            ['id' =>'95', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '601.006', 'uraian' => 'Biaya Pajak Bunga Bank', 'type' => 'D'],
            ['id' =>'96', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '2', 'kdrek' => '601.007', 'uraian' => 'Biaya Surat Tagihan Pajak (STP)', 'type' => 'D'],
            ['id' =>'97', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '3', 'kdrek' => '602', 'uraian' => 'Beban Transportasi', 'type' => 'C'],
            ['id' =>'98', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '3', 'kdrek' => '602.001', 'uraian' => 'Biaya Transportasi Local', 'type' => 'D'],
            ['id' =>'99', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '3', 'kdrek' => '602.002', 'uraian' => 'Biaya Perjalanan Dinas', 'type' => 'D'],
            ['id' =>'100', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '3', 'kdrek' => '602.003', 'uraian' => 'Biaya Pembelian Transportasi', 'type' => 'D'],
            ['id' =>'101', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '3', 'kdrek' => '602.004', 'uraian' => 'Biaya Transportasi Lainnya', 'type' => 'D'],
            ['id' =>'102', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '4', 'kdrek' => '700', 'uraian' => 'Beban Administratif dan Konsumsi Kantor', 'type' => 'C'],
            ['id' =>'103', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '4', 'kdrek' => '700.001', 'uraian' => 'Biaya Sewa Kantor', 'type' => 'D'],
            ['id' =>'104', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '4', 'kdrek' => '700.002', 'uraian' => 'Biaya Perawatan Kantor', 'type' => 'D'],
            ['id' =>'105', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '4', 'kdrek' => '700.003', 'uraian' => 'Biaya Pembangunan Kantor', 'type' => 'D'],
            ['id' =>'106', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '4', 'kdrek' => '700.004', 'uraian' => 'Biaya Pembelian Perlengkapan Kantor', 'type' => 'D'],
            ['id' =>'107', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '4', 'kdrek' => '700.005', 'uraian' => 'Biaya pembelian peralatan kantor ', 'type' => 'D'],
            ['id' =>'108', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '4', 'kdrek' => '700.006', 'uraian' => 'Biaya Print dan Potocopy', 'type' => 'D'],
            ['id' =>'109', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '4', 'kdrek' => '700.007', 'uraian' => 'Biaya Pengiriman ', 'type' => 'D'],
            ['id' =>'110', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '4', 'kdrek' => '700.008', 'uraian' => 'Biaya Meeting', 'type' => 'D'],
            ['id' =>'111', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '4', 'kdrek' => '700.009', 'uraian' => 'Biaya Adm Bank', 'type' => 'D'],
            ['id' =>'112', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '5', 'kdrek' => '701', 'uraian' => 'Beban Tenaga Kerja', 'type' => 'C'],
            ['id' =>'113', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '5', 'kdrek' => '701.001', 'uraian' => 'Biaya Gaji', 'type' => 'D'],
            ['id' =>'114', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '5', 'kdrek' => '701.002', 'uraian' => 'Biaya THR', 'type' => 'D'],
            ['id' =>'115', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '5', 'kdrek' => '701.003', 'uraian' => 'Biaya Tunjangan Kesehatan', 'type' => 'D'],
            ['id' =>'116', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '5', 'kdrek' => '701.004', 'uraian' => 'Biaya Tunjangan Komunikasi', 'type' => 'D'],
            ['id' =>'117', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '5', 'kdrek' => '701.005', 'uraian' => 'Biaya BPJS Kesehatan', 'type' => 'D'],
            ['id' =>'118', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '5', 'kdrek' => '701.006', 'uraian' => 'Biaya Jamsostek/ BPJS TK', 'type' => 'D'],
            ['id' =>'119', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '6', 'kdrek' => '702', 'uraian' => 'Beban Profesional', 'type' => 'C'],
            ['id' =>'120', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '6', 'kdrek' => '702.001', 'uraian' => 'Biaya Notaris', 'type' => 'D'],
            ['id' =>'121', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '6', 'kdrek' => '702.002', 'uraian' => 'Biaya Konsultan', 'type' => 'D'],
            ['id' =>'122', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '6', 'kdrek' => '702.003', 'uraian' => 'Biaya Training', 'type' => 'D'],
            ['id' =>'123', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '6', 'kdrek' => '702.004', 'uraian' => 'Biaya Jasa Lain- Lain', 'type' => 'D'],
            ['id' =>'124', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '7', 'kdrek' => '703', 'uraian' => 'Biaya Lain-Lain', 'type' => 'C'],
            ['id' =>'125', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '7', 'kdrek' => '704.001', 'uraian' => 'Biaya Lainnya', 'type' => 'D'],
            ['id' =>'126', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '7', 'kdrek' => '704.002', 'uraian' => 'Biaya Bonus', 'type' => 'D'],
            ['id' =>'127', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '7', 'kdrek' => '704.003', 'uraian' => 'Biaya Desain', 'type' => 'D'],
            ['id' =>'128', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '7', 'kdrek' => '704.004', 'uraian' => 'Biaya pembuatan aplikasi', 'type' => 'D'],
            ['id' =>'129', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '7', 'kdrek' => '704.005', 'uraian' => 'Biaya interior', 'type' => 'D'],
            ['id' =>'130', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '7', 'kdrek' => '704.006', 'uraian' => 'Biaya pemasangan instalasi', 'type' => 'D'],
            ['id' =>'131', 'kdrek1' => '5', 'kdrek2' => '1', 'kdrek3' => '7', 'kdrek' => '704.007', 'uraian' => 'Biaya material', 'type' => 'D'],
            ['id' =>'132', 'kdrek1' => '5', 'kdrek2' => '2', 'kdrek3' => '0', 'kdrek' => '0', 'uraian' => 'Beban Non - Operasional', 'type' => 'S'],
            ['id' =>'133', 'kdrek1' => '5', 'kdrek2' => '2', 'kdrek3' => '1', 'kdrek' => '800', 'uraian' => 'Beban Depresiasi', 'type' => 'C'],
            ['id' =>'134', 'kdrek1' => '5', 'kdrek2' => '2', 'kdrek3' => '1', 'kdrek' => '800.001', 'uraian' => 'Biaya Depresiasi Renovasi dan Lainnya', 'type' => 'D'],
            ['id' =>'135', 'kdrek1' => '5', 'kdrek2' => '2', 'kdrek3' => '1', 'kdrek' => '800.002', 'uraian' => 'Biaya Depresiasi Furniture dan Fixture', 'type' => 'D'],
            ['id' =>'136', 'kdrek1' => '5', 'kdrek2' => '2', 'kdrek3' => '1', 'kdrek' => '800.003', 'uraian' => 'Biaya Depresiasi Komputer & Perlengkapan Kantor', 'type' => 'D'],
            ['id' =>'137', 'kdrek1' => '5', 'kdrek2' => '2', 'kdrek3' => '2', 'kdrek' => '801', 'uraian' => 'Beban Keuangan  ', 'type' => 'C'],
            ['id' =>'138', 'kdrek1' => '5', 'kdrek2' => '2', 'kdrek3' => '2', 'kdrek' => '800.001', 'uraian' => 'Biaya Keuangan Lainnya', 'type' => 'D'],
        ]);
    }
}
