<?php

namespace App\Http\Controllers;

use App\Helpers\LogActivity;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\RateLimiter;

use App\Models\User;
use Hash;
use Session, Alert, DB;
use Spatie\Permission\Models\Permission;

class AuthController extends Controller
{
    //
    public function index()
    {

        return view('auth.login');
    }

    /**
     * Write code on Method
     *
     * @return response()
     */
    public function postLogin(Request $request)
    {
        $request->validate([
            'username' => 'required',
            'password' => 'required',
        ],[
            'username.required' => 'username Tidak boleh Kosong',
            'password.required' => 'Password Tidak boleh Kosong'

        ]);

        $credentials =[
            'username' => $request->username,
            'password' => $request->password,
            'status' => 1
        ];

        if (Auth::attempt($credentials)) {
            toast('Login berhasil','success')
            ->autoClose(3000)
            ->timerProgressBar();

            return redirect()->intended('dashboard')
                        ->withSuccess('You have Successfully loggedin');
        }

        else{
            $user = User::where('username', $request->username);

            if (empty($user->first())) {
                return redirect()
                ->back()
                ->withInput()
                ->withErrors(['notfound' => 'Akun Tidak Ditemukan']);
            }

            return redirect()
                        ->back()
                        ->withInput()
                        ->withErrors(['wrong' => 'Data Tidak Sesuai']);
        }

        return redirect('login');

    }

    public function postRegister(Request $request)
    {
        $input = $request->all();

        $input['password'] = bcrypt($input['password']);

        $user = User::create($input);

        $user->givePermissionTo(Permission::all());

        // event(UserWasCreated::class);

        if (Auth::attempt($request->only('username', 'password'))) {
            return redirect()
                ->route('dashboard')
                ->with('Welcome! Your account has been successfully created!');
        }

        // Redirect
        return redirect()
            // To the previous page (probably the one generated by a `getRegister` method)
            ->back()
            // And with the input data (so that the form will get populated again)
            ->withInput();
    }

    /**
     * Write code on Method
     *
     * @return response()
     */

    /**
     * Write code on Method
     *
     * @return response()
     */
    public function dashboard()
    {
        if(Auth::check()){
            if (Auth::user()->roles[0]->name == 'user') {
                return redirect()->route('booking.index');
            }


            return view('index');
        }


        return redirect("login")->withSuccess('Opps! You do not have access');
    }


    /**
     * Write code on Method
     *
     * @return response()
     */
    public function logout() {
        Session::flush();
        Auth::logout();

        return Redirect('login');
    }
}
